### ISSUE TITLE
PDF Version

### ISSUE THREAD

**Issue by juanvera** [blechturm/MITx_capstone_2#2]
Hi Thomas:
Is it possible that you push the pdf version of the MITx_capstone_2 cheatsheet? I am having troubles converting the text to pdf.
Thanks!

**Comment by connectwithprakash** [comment]
#3 I have added the pdf version of the cheatsheet. Hoppe that @blechturm accepts this PR.

**Comment by connectwithprakash** [comment]
#3 I have added the pdf version of the cheatsheet. Hoppe that @blechturm accepts this PR.

**Comment by blechturm** [comment]
Hi! Thanks for putting the PDF in here!
